<?php
namespace App\Exceptions; use App\Library\Response; use Exception; use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler; class Handler extends ExceptionHandler { protected $dontReport = array(); protected $dontFlash = array('password', 'password_confirmation'); public function report(Exception $sp7c25f3) { parent::report($sp7c25f3); } public function render($spceaf29, Exception $spa0e498) { if ($spa0e498 instanceof \Illuminate\Database\Eloquent\ModelNotFoundException) { return $spceaf29->expectsJson() ? response()->json(array('message' => '记录未找到'), 404) : response()->view('errors._', array('code' => 404, 'message' => '记录未找到'), 404); } elseif ($spa0e498 instanceof \Illuminate\Auth\AuthenticationException) { return $spceaf29->expectsJson() ? response()->json(array('message' => '请先登录'), 401) : response()->view('errors._', array('code' => 401, 'message' => '请先登录'), 401); } elseif ($spa0e498 instanceof \Illuminate\Auth\Access\AuthorizationException) { return $spceaf29->expectsJson() ? response()->json(array('message' => '未授权的操作'), 403) : response()->view('errors._', array('code' => 403, 'message' => '未授权的操作'), 403); } elseif ($spa0e498 instanceof \Illuminate\Validation\ValidationException) { return parent::render($spceaf29, $spa0e498); } elseif ($spa0e498 instanceof \Illuminate\Session\TokenMismatchException) { return $spceaf29->expectsJson() ? response()->json(array('message' => '请刷新页面后重试'), 403) : response()->view('errors._', array('code' => 403, 'message' => '请刷新页面后重试'), 403); } elseif ($spa0e498 instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException) { return $spceaf29->expectsJson() ? response()->json(array('message' => '页面未找到'), 404) : response()->view('errors._', array('code' => 404, 'message' => '页面未找到'), 404); } elseif ($spa0e498 instanceof \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException) { return $spceaf29->expectsJson() ? response()->json(array('message' => '请求方法不允许'), 405) : response()->view('errors._', array('code' => 405, 'message' => '请求方法不允许'), 405); } elseif ($spa0e498 instanceof \Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException) { \Log::error('Uncaught a ServiceUnavailableHttpException', array('Exception' => $spa0e498)); return $spceaf29->expectsJson() ? response()->json(array('message' => '当前服务不可用，请稍后重试'), 503) : response()->view('errors._', array('code' => 503, 'message' => '当前服务不可用，请稍后重试'), 503); } \Log::error('Uncaught Exception', array('Exception' => $spa0e498)); if (config('app.debug')) { return parent::render($spceaf29, $spa0e498); } else { return $spceaf29->expectsJson() ? response()->json(array('message' => '未知错误，请联系客服'), 500) : response()->view('errors._', array('code' => 500, 'message' => '未知错误，请联系客服'), 500); } } }